
// *** THIS HEADER IS AUTO GENERATED. DO NOT EDIT IT ***
#include           "globalCore.h"
#include           "externalCore.h"
// *** THIS HEADER IS AUTO GENERATED. DO NOT EDIT IT ***

      
    

#include "sexpIO.h"
char  *RF_sexpStringIO[RF_SEXP_CNT] = {
  "",              
  "",              
  "allEnsbCHF",    
  "oobEnsbCHF",    
  "allEnsbCIF",    
  "oobEnsbCIF",    
  "allEnsbSRV",    
  "oobEnsbSRV",    
  "allEnsbMRT",    
  "oobEnsbMRT",    
  "allEnsbCLS",    
  "oobEnsbCLS",    
  "allEnsbRGR",    
  "oobEnsbRGR",    
  "perfSurv",      
  "perfClas",      
  "perfRegr",      
  "proximity",     
  "leafCount",     
  "seed",          
  "seedVimp",      
  "allEnsbQNT",    
  "oobEnsbQNT",    
  "blockSurv",     
  "blockClas",     
  "blockRegr",     
  "vimpSurv",      
  "vimpClas",      
  "vimpRegr",      
  "imputation",    
  "",              
  "varUsed",       
  "splitDepth",    
  "nodeMembership",
  "pstnMembership",
  "bootMembership",
  "rmbrMembership",
  "ambrMembership",
  "tnRCNT",        
  "tnACNT",        
  "spltST",        
  "dpthST",        
  "weight",        
  "tnSURV",        
  "tnMORT",        
  "tnNLSN",        
  "tnCSHZ",        
  "tnCIFN",        
  "tnREGR",        
  "tnCLAS",        
  "tnKHZF",        
  "cseRegr",       
  "csvRegr",       
  "cseClas",       
  "csvClas",       
  "",              
  "partialSurv",   
  "partialClas",   
  "partialRegr",   
  "distance",      
  "treeID",        
  "nodeID",        
  "parmID",        
  "contPT",        
  "mwcpSZ",        
  "mwcpPT",        
  "mwcpCT",        
  "hcDim",         
  "contPTR",       
  "pairCT",        
  "augmXone",      
  "augmXtwo",      
  "augmXS",        
  "emprRisk",      
  "oobEmprRisk",   
  "splitStatLOT",  
  "holdoutBlk",    
  "holdoutSurv",   
  "holdoutClas",   
  "holdoutRegr",   
  "allEnsbKHZ",    
  "oobEnsbKHZ",    
  "sythSZ",        
  "treeIDsyth",    
  "nodeIDsyth",    
  "parmIDsyth",    
  "contPTsyth",    
  "mwcpSZsyth",    
  "mwcpPTsyth",        
  "mwcpCTsyth",        
  "hcDimsyth",         
  "contPTRsyth",       
  "nodeCountSyth",     
  "nodeMembershipTDC", 
  "cseDen",            
  "csvDen",            
  "blnodeID",          
  "brnodeID",          
  "fsrecID",           
  "nodeSZ",            
  "caseDepth",         
  "optLoGrow",         
  "optHiGrow",         
  "cTimeInternal"      
};
