#define VP_TREE_ID     0  
#define VP_NODE_ID     1  
#define VP_XVAR_ID     2  
#define VP_OOBG_CT     3  
#define VP_STAT_IMP    4  
#define VP_STAT_COMPL  5  
#define VP_STAT_OOB    6  
#define VP_OOBG_MEM    7  
#define VP_COMP_MEM    8  
#define VP_COMP_CT     9  
#define VP_OPT_CMP     0x00000001 
#define VP_OPT_OOB     0x00000002 
