#ifndef RF_STACK_OUTPUT_H
#define RF_STACK_OUTPUT_H
void stackStrengthObjectsPtrOnly(char       mode,
                                 uint       ntree,
                                 uint       maxTree,
                                 uint      *tLeafCount,
                                 uint      *strengthTreeCount,
                                 uint     **strengthTreeID,
                                 uint     **branchCount,
                                 uint    ***branchID,
                                 uint    ***oobCount,
                                 uint    ***xReleaseCount,
                                 uint   ****xReleaseIDArray,
                                 uint   ****complementCount,
                                 uint    ***proxyIndv,
                                 uint    ***proxyIndvDepth);
void unstackStrengthObjectsPtrOnly(char      mode,
                                   uint      strengthTreeCount,
                                   uint     *strengthTreeID,
                                   uint     *branchCount,
                                   uint    **branchID,
                                   uint    **oobCount,
                                   uint    **xReleaseCount,
                                   uint   ***xReleaseIDArray,
                                   uint   ***complementCount,
                                   uint    **proxyIndv,
                                   uint    **proxyIndvDepth);
void selectTrees(uint    ntree,
                 uint    strengthTreeCount,
                 uint   *tLeafCount,
                 uint   *strengthTreeID);
void selectBranches(uint    b,
                    uint    treeID,
                    uint    maxRulesTree,
                    uint    leafCount,
                    uint   *branchCount,
                    uint  **branchID,
                    uint  **oobCount,
                    uint  **xReleaseCount,
                    uint ***xReleaseIDArray,
                    uint ***complementCount,
                    uint  **proxyIndv,
                    uint  **proxyIndvDepth);
void freeStrengthBranchIDVectors(uint    strengthTreeCount,
                                 uint   *branchCount,
                                 uint  **branchID,
                                 uint  **oobCount,
                                 uint  **xReleaseCount,
                                 uint ***xReleaseIDArray,
                                 uint ***complementCount,
                                 uint  **proxyIndv,
                                 uint  **proxyIndvDepth);
void freeReleaseIDArray(uint   branchCount,
                        uint  *xReleaseCount,
                        uint **xReleaseIDArray,
                        uint **complementCount,
                        uint  *proxyIndvDepth);
void writeStrengthArray(uint     *strengthTreeID,
                        uint      strengthTreeCount,
                        uint    **branchID,
                        uint     *branchCount,
                        uint    **oobCount,
                        uint   ***complementCount,
                        uint    **xReleaseCount,
                        uint   ***xReleaseIDArray,
                        uint     *treeID,
                        uint     *nodeID,
                        uint     *xReleaseID,
                        void     *oobCT,
                        void     *releaseStat);
#endif
